### ISSUE TITLE
Prosím nezávisle na platformě

### ISSUE THREAD

**Issue by ptakopysk** [gortibaldik/Text-comprehension#1]
https://github.com/gortibaldik/TF-IDF/blob/7d328b20f67e13d69bdd5d085a120e1cb1f09a78/dataset_loader.py#L28

Zde je natvrdo backslash.

**Comment by ptakopysk** [comment]
Aha tohle je asi zrovna dost dočasné, že. Ale stejně :-)

**Comment by gortibaldik** [comment]
dataset_loader.py je už prerobený na prácu so zipfile. Aj tak sa ale ukázal jeden problém. Zipfile natvrdo pracuje s posix paths, teda s forward slashes. Preto som použil pathlib a z nej PurePosixPath, aby som nikde nepridával backslashe, alebo forward slashe natvrdo, ale používam na to práve tento modul.
