### ISSUE TITLE
Problémy s kódováním

### ISSUE THREAD

**Issue by ptakopysk** [gortibaldik/Text-comprehension#2]
https://github.com/gortibaldik/TF-IDF/blob/7d328b20f67e13d69bdd5d085a120e1cb1f09a78/dataset_loader.py#L52

Prosím specifikovat encoding (asi encoding='iso-8859-1' ale nevím jistě), padá mi to s `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 9285: invalid start byte`

**Comment by gortibaldik** [comment]
Áno, s encoding='iso-8859-1' to už nepadá, preto som ho tam zahardcodoval a pridal exception handling, keby sa niekedy v budúcnosti do datasetu pridalo niečo kódované inak.
