### ISSUE TITLE
používat vestavěné věci?

### ISSUE THREAD

**Issue by ptakopysk** [gortibaldik/Text-comprehension#3]
https://github.com/gortibaldik/TF-IDF/blob/7d328b20f67e13d69bdd5d085a120e1cb1f09a78/document_preprocessor.py#L88

Použít `string.punctuation`?

**Comment by ptakopysk** [comment]
A rychlejší je to dělat bez toho for-cyklu, viz např. https://www.quora.com/How-do-I-remove-punctuation-from-a-Python-string

**Comment by gortibaldik** [comment]
Nechcem použiť string.punctuation, pretože ten obsahuje aj apostrof \' , ktorý nechcem odstraňovať, pretože by nefungovalo odstraňovanie stopwords. 

Cases : 1. remove string.punctuation -> remove stopwords by najprv z "don't" vytvorilo "dont", ktoré by dataset nltk.corpus.stopwords nerozpoznal ( a je jednoduchšie znovu implementovať string.punctuation ako nltk.corpus.stopwords )

2. remove stopwords -> remove string.punctuation by síce už odstránilo "don't", ale neodstránilo by napríklad "don't!"

Odpoveď z  https://www.quora.com/How-do-I-remove-punctuation-from-a-Python-string som použil, avšak tá bola napísaná v pythone 2. Kód, ktorý som písal je pre python 3, preto som ani neuvažoval o nejakej spätnej kompatibilite, zrejme je toho oveľa viac, čo nie je spätne kompatibilné. Použil som odpoveď odtiaľto : https://stackoverflow.com/questions/23175809/str-translate-gives-typeerror-translate-takes-one-argument-2-given-worked-i
